// Bake traced green polygons + aim points into src/greenData.js.
//
// Reads scripts/greens.geojson (18 hand-traced greens, LineString or Polygon,
// arbitrary order). For each: cleans the ring, matches it to the nearest hole
// green in courseData, and computes the pole of inaccessibility (largest
// inscribed circle) via polylabel in a local metre projection.
//
// Run with:  npm run bake:greens

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import polylabel from 'polylabel';
import { courseData } from '../src/courseData.js';

const dir = dirname(fileURLToPath(import.meta.url));
const SRC = join(dir, 'greens.geojson');
const OUT = join(dir, '..', 'src', 'greenData.js');

const fail = (msg) => { console.error('bake:greens FAILED — ' + msg); process.exit(1); };

// Equirectangular distance (metres) between two { lat, lng }.
const distM = (a, b) => {
  const lat0 = ((a.lat + b.lat) / 2) * Math.PI / 180;
  const x = (a.lng - b.lng) * 111320 * Math.cos(lat0);
  const y = (a.lat - b.lat) * 110540;
  return Math.hypot(x, y);
};

// Cleaned coordinate ring ({lat,lng}[]) for a feature: outer ring, no
// consecutive duplicates, no closing duplicate; requires >= 5 vertices.
function ringOf(feature, i) {
  const g = feature.geometry;
  let coords;
  if (g.type === 'LineString') coords = g.coordinates;
  else if (g.type === 'Polygon') coords = g.coordinates[0];
  else return fail(`feature ${i}: unsupported geometry type "${g.type}"`);

  const pts = coords.map((c) => ({ lat: c[1], lng: c[0] })); // GeoJSON is [lng, lat]
  const ring = [];
  for (const p of pts) {
    const last = ring[ring.length - 1];
    if (!last || last.lat !== p.lat || last.lng !== p.lng) ring.push(p);
  }
  if (ring.length > 1) {
    const f = ring[0], l = ring[ring.length - 1];
    if (f.lat === l.lat && f.lng === l.lng) ring.pop();
  }
  if (ring.length < 5) return fail(`feature ${i}: only ${ring.length} vertices after cleaning (need >= 5)`);
  return ring;
}

const centroidOf = (ring) => ({
  lat: ring.reduce((s, p) => s + p.lat, 0) / ring.length,
  lng: ring.reduce((s, p) => s + p.lng, 0) / ring.length,
});

// Pole of inaccessibility for a ring, projected to local metres around `origin`.
function aimOf(ring, origin) {
  const lat0 = origin.lat, lng0 = origin.lng;
  const mx = 111320 * Math.cos(lat0 * Math.PI / 180), my = 110540;
  const projRing = ring.map((p) => [(p.lng - lng0) * mx, (p.lat - lat0) * my]);
  const res = polylabel([projRing], 0.1);
  return {
    aim: {
      lat: +(lat0 + res[1] / my).toFixed(7),
      lng: +(lng0 + res[0] / mx).toFixed(7),
    },
    aimRadius: Math.round(res.distance * 10) / 10,
  };
}

function main() {
  const gj = JSON.parse(readFileSync(SRC, 'utf8'));
  if (!gj.features || gj.features.length !== 18) {
    return fail(`expected 18 features, got ${gj.features ? gj.features.length : 0}`);
  }

  const feats = gj.features.map((f, i) => {
    const ring = ringOf(f, i);
    return { ring, centroid: centroidOf(ring) };
  });

  // Assign each feature to its nearest hole green.
  const holeFeatures = Array.from({ length: 18 }, () => []);
  feats.forEach((feat, fi) => {
    let best = -1, bestD = Infinity;
    courseData.forEach((h, hi) => {
      const d = distM(feat.centroid, h.greenLocation);
      if (d < bestD) { bestD = d; best = hi; }
    });
    feat.dist = bestD;
    holeFeatures[best].push(fi);
  });

  const zero = [], multi = [];
  holeFeatures.forEach((list, hi) => {
    if (list.length === 0) zero.push(hi + 1);
    else if (list.length > 1) multi.push(hi + 1);
  });
  if (zero.length || multi.length) {
    return fail(`green↔hole matching ambiguous. Holes with NO green: [${zero.join(', ')}]; holes with MULTIPLE greens: [${multi.join(', ')}].`);
  }

  // Build output in courseData order (hole 1 = index 0).
  const entries = holeFeatures.map((list) => {
    const feat = feats[list[0]];
    const { aim, aimRadius } = aimOf(feat.ring, feat.centroid);
    return { ring: feat.ring, aim, aimRadius, dist: feat.dist };
  });

  console.log('Hole  verts  aimRadius(m)  matchDist(m)');
  entries.forEach((e, i) => {
    console.log(`${String(i + 1).padStart(2)}    ${String(e.ring.length).padStart(4)}    ${String(e.aimRadius).padStart(8)}     ${e.dist.toFixed(1).padStart(7)}`);
  });

  const fmtPt = (p) => `{ lat: ${p.lat}, lng: ${p.lng} }`;
  const body = entries.map((e) => {
    const poly = e.ring.map(fmtPt).join(', ');
    return `  { polygon: [${poly}], aim: ${fmtPt(e.aim)}, aimRadius: ${e.aimRadius} }`;
  }).join(',\n');

  const out = `// AUTO-GENERATED by scripts/bakeGreens.mjs — do not edit by hand.
// Traced green polygon + pole-of-inaccessibility aim point (largest inscribed
// circle, aimRadius in metres) per hole. Source: scripts/greens.geojson.
// Index matches courseData order (hole 1 = index 0).
export const greenData = [
${body}
];
`;
  writeFileSync(OUT, out, 'utf8');
  console.log('\nWrote ' + OUT);
}

main();
