// Bake traced fairway + bunker polygons into src/featureData.js.
//
// Reads scripts/fariways.geojson and scripts/sand.geojson (hand-traced Polygon
// features), cleans each outer ring and writes them as { lat, lng } arrays.
// Used at runtime to classify where a GPS shot mark landed (Snjallskrá).
//
// Run with:  npm run bake:features

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const dir = dirname(fileURLToPath(import.meta.url));
const OUT = join(dir, '..', 'src', 'featureData.js');

const fail = (msg) => { console.error('bake:features FAILED — ' + msg); process.exit(1); };

// Cleaned outer ring ({lat,lng}[], 6 decimals) for a Polygon feature: no
// consecutive duplicates, no closing duplicate; requires >= 4 vertices.
function ringOf(feature, file, i) {
  const g = feature.geometry;
  if (g.type !== 'Polygon') return fail(`${file} feature ${i}: unsupported geometry type "${g.type}"`);
  const pts = g.coordinates[0].map((c) => ({
    lat: Math.round(c[1] * 1e6) / 1e6,
    lng: Math.round(c[0] * 1e6) / 1e6,
  })); // GeoJSON is [lng, lat]
  const ring = [];
  for (const p of pts) {
    const last = ring[ring.length - 1];
    if (!last || last.lat !== p.lat || last.lng !== p.lng) ring.push(p);
  }
  if (ring.length > 1) {
    const f = ring[0], l = ring[ring.length - 1];
    if (f.lat === l.lat && f.lng === l.lng) ring.pop();
  }
  if (ring.length < 4) return fail(`${file} feature ${i}: only ${ring.length} vertices after cleaning (need >= 4)`);
  return ring;
}

function ringsFrom(file) {
  const geo = JSON.parse(readFileSync(join(dir, file), 'utf8'));
  if (!geo.features || !geo.features.length) return fail(`${file}: no features`);
  return geo.features.map((f, i) => ringOf(f, file, i));
}

const fairways = ringsFrom('fariways.geojson');
const bunkers = ringsFrom('sand.geojson');

const fmtRing = (ring) =>
  '[' + ring.map((p) => `{ lat: ${p.lat}, lng: ${p.lng} }`).join(', ') + ']';

const out =
  '// AUTO-GENERATED by scripts/bakeFeatures.mjs — do not edit by hand.\n' +
  '// Traced fairway + bunker polygons ({ lat, lng } outer rings). Sources:\n' +
  '// scripts/fariways.geojson and scripts/sand.geojson (hand-traced).\n' +
  'export const featureData = {\n' +
  '  fairways: [\n' +
  fairways.map((r) => '    ' + fmtRing(r) + ',').join('\n') + '\n' +
  '  ],\n' +
  '  bunkers: [\n' +
  bunkers.map((r) => '    ' + fmtRing(r) + ',').join('\n') + '\n' +
  '  ],\n' +
  '};\n';

writeFileSync(OUT, out);
console.log(`bake:features OK — ${fairways.length} fairways, ${bunkers.length} bunkers -> src/featureData.js`);
