// Bake traced fairway + bunker polygons AND per-hole aim points into
// src/featureData.js.
//
// Reads scripts/fariways.geojson and scripts/sand.geojson (hand-traced Polygon
// features), cleans each outer ring and writes them as { lat, lng } arrays.
// Used at runtime to classify where a GPS shot mark landed (Snjallskrá).
//
// Also reads scripts/aims.geojson: one Point per par-4/5 hole IN HOLE ORDER —
// the "best possible safe tee shot" landing spot. Each aim gets a derived
// dogleg angle (bearing change tee→aim vs aim→green; + = turns right). Sanity
// checks catch out-of-order points.
//
// Run with:  npm run bake:features

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { courseData } from '../src/courseData.js';

const dir = dirname(fileURLToPath(import.meta.url));
const OUT = join(dir, '..', 'src', 'featureData.js');

const fail = (msg) => { console.error('bake:features FAILED — ' + msg); process.exit(1); };

// Equirectangular distance (metres) and compass bearing between { lat, lng }.
const distM = (a, b) => {
  const lat0 = ((a.lat + b.lat) / 2) * Math.PI / 180;
  return Math.hypot((a.lng - b.lng) * 111320 * Math.cos(lat0), (a.lat - b.lat) * 110540);
};
const bearing = (a, b) => {
  const t = (d) => d * Math.PI / 180;
  const y = Math.sin(t(b.lng - a.lng)) * Math.cos(t(b.lat));
  const x = Math.cos(t(a.lat)) * Math.sin(t(b.lat)) - Math.sin(t(a.lat)) * Math.cos(t(b.lat)) * Math.cos(t(b.lng - a.lng));
  return (Math.atan2(y, x) * 180 / Math.PI + 360) % 360;
};
const angDiff = (d) => ((d + 540) % 360) - 180; // normalize to [-180, 180]

// Cleaned outer ring ({lat,lng}[], 6 decimals) for a Polygon feature: no
// consecutive duplicates, no closing duplicate; requires >= 4 vertices.
function ringOf(feature, file, i) {
  const g = feature.geometry;
  if (g.type !== 'Polygon') return fail(`${file} feature ${i}: unsupported geometry type "${g.type}"`);
  const pts = g.coordinates[0].map((c) => ({
    lat: Math.round(c[1] * 1e6) / 1e6,
    lng: Math.round(c[0] * 1e6) / 1e6,
  })); // GeoJSON is [lng, lat]
  const ring = [];
  for (const p of pts) {
    const last = ring[ring.length - 1];
    if (!last || last.lat !== p.lat || last.lng !== p.lng) ring.push(p);
  }
  if (ring.length > 1) {
    const f = ring[0], l = ring[ring.length - 1];
    if (f.lat === l.lat && f.lng === l.lng) ring.pop();
  }
  if (ring.length < 4) return fail(`${file} feature ${i}: only ${ring.length} vertices after cleaning (need >= 4)`);
  return ring;
}

function ringsFrom(file) {
  const geo = JSON.parse(readFileSync(join(dir, file), 'utf8'));
  if (!geo.features || !geo.features.length) return fail(`${file}: no features`);
  return geo.features.map((f, i) => ringOf(f, file, i));
}

const fairways = ringsFrom('fariways.geojson');
const bunkers = ringsFrom('sand.geojson');

// --- AIM POINTS ---
const aimGeo = JSON.parse(readFileSync(join(dir, 'aims.geojson'), 'utf8'));
const aimPts = aimGeo.features.map((f, i) => {
  if (f.geometry.type !== 'Point') return fail(`aims.geojson feature ${i}: not a Point`);
  const [lng, lat] = f.geometry.coordinates;
  return { lat: Math.round(lat * 1e7) / 1e7, lng: Math.round(lng * 1e7) / 1e7 };
});
const par45 = courseData.filter((h) => h.par > 3);
if (aimPts.length !== par45.length) {
  fail(`aims.geojson has ${aimPts.length} points but the course has ${par45.length} par 4/5 holes`);
}

// One entry per hole (null on par 3s): aim coords + signed dogleg degrees.
const aims = courseData.map(() => null);
par45.forEach((h, i) => {
  const a = aimPts[i], tee = h.teeLocation, g = h.greenLocation;
  // Sanity: the aim must sit broadly down the hole, short of the green.
  const dev = angDiff(bearing(tee, a) - bearing(tee, g));
  if (Math.abs(dev) > 45) fail(`hole ${h.hole}: aim is ${Math.round(dev)}° off the tee->green line — points out of order?`);
  if (distM(tee, a) > distM(tee, g)) fail(`hole ${h.hole}: aim is farther from the tee than the green — points out of order?`);
  const dogleg = Math.round(angDiff(bearing(a, g) - bearing(tee, a)));
  aims[courseData.indexOf(h)] = { lat: a.lat, lng: a.lng, dogleg };
});

const fmtRing = (ring) =>
  '[' + ring.map((p) => `{ lat: ${p.lat}, lng: ${p.lng} }`).join(', ') + ']';

const out =
  '// AUTO-GENERATED by scripts/bakeFeatures.mjs — do not edit by hand.\n' +
  '// Traced fairway + bunker polygons ({ lat, lng } outer rings) and per-hole\n' +
  '// aim points (ideal safe tee shot; dogleg = signed bearing change in degrees,\n' +
  '// + turns right, − turns left; null on par 3s). Sources: scripts/\n' +
  '// fariways.geojson, sand.geojson, aims.geojson (all hand-traced).\n' +
  'export const featureData = {\n' +
  '  fairways: [\n' +
  fairways.map((r) => '    ' + fmtRing(r) + ',').join('\n') + '\n' +
  '  ],\n' +
  '  bunkers: [\n' +
  bunkers.map((r) => '    ' + fmtRing(r) + ',').join('\n') + '\n' +
  '  ],\n' +
  '  aims: [\n' +
  aims.map((a) => '    ' + (a ? `{ lat: ${a.lat}, lng: ${a.lng}, dogleg: ${a.dogleg} }` : 'null') + ',').join('\n') + '\n' +
  '  ],\n' +
  '};\n';

writeFileSync(OUT, out);
console.log(`bake:features OK — ${fairways.length} fairways, ${bunkers.length} bunkers, ${aimPts.length} aims -> src/featureData.js`);
